### ISSUE TITLE
Project doesn't launch on clicking Open Application

### ISSUE THREAD

**Issue by rodneytamblyn** [trevordevore/dataview_demo#4]
Hi Trevor,

Looks like this demo is broken at the moment.  Tested 10.15.5 OSX   LC Community 9.6.1

Tried:
- quit livecode community 9.6.1
- create folder on disk, cd to folder in terminal
- clone https://github.com/trevordevore/dataview_demo.git to folder
- open folder dataview_demo/app/ and launch standalone.livecode
- click Open Application button.  

Nothing happens....

**Comment by trevordevore** [comment]
@rodneytamblyn You probably didn't pull the submodules in. Take a look at the README as it points you to a .zip file with all of the files necessary to run the demo:

https://github.com/trevordevore/dataview_demo

That link points to the current release available from the Releases page: https://github.com/trevordevore/dataview_demo/releases/

**Comment by rodneytamblyn** [comment]
Ok, will do. Note though that I used git clone to download, so would have expected it to checkout all required files?

--
Rodney Tamblyn
Co- Founder & CEO | OceanBrowser Ltd
+64 34742102 |  @ocnb3
https://nz.linkedin.com/in/rodneytamblyn

Beautiful study for lifelong learning
http://www.ob3.io

**Comment by trevordevore** [comment]
Nope. You have to use `git clone --recurse-submodules` to include submodules.

**Comment by rodneytamblyn** [comment]
Yep - that's it!   Can I suggest updating readme "Usage" to note git instructions
(`git clone --recurse-submodules` to include submodules) if checking out the project via Git.  As default you'll get if clicking the git download path in github is just git checkout.

**Comment by trevordevore** [comment]
You are welcome to update the README and submit a PR.
